import type { Incident, IncidentEdge } from "./types";

// Shown only when the backend is unreachable, always behind a visible "demo
// data" label. Lifecycle values match the backend CHECK constraint exactly
// (OPEN / ACKNOWLEDGED / QUIESCENT / RESOLVED).
const now = Date.now();
const minutesAgo = (m: number) => new Date(now - m * 60_000).toISOString();

export const DEMO_INCIDENTS: Incident[] = [
  {
    incident_id: "demo-1",
    title: "payment-api · ServiceDown",
    summary: "Health check failing on 2 of 3 instances.",
    severity: "critical",
    status: "OPEN",
    alert_count: 47,
    first_alert_at: minutesAgo(18),
    last_alert_at: minutesAgo(1),
    ewma_rate: 3.8,
    route_decision: "pagerduty",
    quiet_at_ms: now + 14 * 60_000,
    root_cause_hint: "deploy at 10:02 correlates with onset",
    created_at: minutesAgo(18),
    updated_at: minutesAgo(1),
  },
  {
    incident_id: "demo-2",
    title: "payment-api · HighCPUUsage",
    summary: "CPU above 90% on payment-api-1 and payment-api-2.",
    severity: "high",
    status: "OPEN",
    alert_count: 112,
    first_alert_at: minutesAgo(22),
    last_alert_at: minutesAgo(2),
    ewma_rate: 5.1,
    route_decision: "slack",
    quiet_at_ms: now + 14 * 60_000,
    root_cause_hint: "downstream of payment-api · ServiceDown",
    created_at: minutesAgo(22),
    updated_at: minutesAgo(2),
  },
  {
    incident_id: "demo-3",
    title: "checkout-db · ReplicationLagHigh",
    summary: "Replica lag exceeded the 30s threshold.",
    severity: "high",
    status: "ACKNOWLEDGED",
    alert_count: 31,
    first_alert_at: minutesAgo(14),
    last_alert_at: minutesAgo(1),
    ewma_rate: 2.4,
    route_decision: "pagerduty",
    quiet_at_ms: now + 14 * 60_000,
    root_cause_hint: "downstream of payment-api · HighCPUUsage",
    created_at: minutesAgo(14),
    updated_at: minutesAgo(1),
  },
  {
    incident_id: "demo-4",
    title: "auth-service · ElevatedLatencyP99",
    summary: null,
    severity: "medium",
    status: "ACKNOWLEDGED",
    alert_count: 26,
    first_alert_at: minutesAgo(41),
    last_alert_at: minutesAgo(9),
    ewma_rate: 1.1,
    route_decision: "slack",
    quiet_at_ms: now + 14 * 60_000,
    root_cause_hint: null,
    created_at: minutesAgo(41),
    updated_at: minutesAgo(9),
  },
  {
    incident_id: "demo-5",
    title: "search-index · QueueDepthGrowing",
    summary: null,
    severity: "medium",
    status: "QUIESCENT",
    alert_count: 18,
    first_alert_at: minutesAgo(52),
    last_alert_at: minutesAgo(21),
    ewma_rate: 0.3,
    route_decision: "slack",
    quiet_at_ms: now + 14 * 60_000,
    root_cause_hint: null,
    created_at: minutesAgo(52),
    updated_at: minutesAgo(21),
  },
  {
    incident_id: "demo-6",
    title: "image-resizer · DiskUsageWarning",
    summary: null,
    severity: "low",
    status: "QUIESCENT",
    alert_count: 6,
    first_alert_at: minutesAgo(58),
    last_alert_at: minutesAgo(30),
    ewma_rate: 0.05,
    route_decision: "email",
    quiet_at_ms: now + 14 * 60_000,
    root_cause_hint: null,
    created_at: minutesAgo(58),
    updated_at: minutesAgo(30),
  },
  {
    incident_id: "demo-7",
    title: "notifications-worker · PodCrashLoop",
    summary: "Resolved after rollback to the previous image.",
    severity: "high",
    status: "RESOLVED",
    alert_count: 84,
    first_alert_at: minutesAgo(120),
    last_alert_at: minutesAgo(75),
    ewma_rate: 0,
    route_decision: "pagerduty",
    quiet_at_ms: now + 14 * 60_000,
    root_cause_hint: "image rollback resolved this",
    created_at: minutesAgo(120),
    updated_at: minutesAgo(75),
  },
  {
    incident_id: "demo-8",
    title: "payment-api · RateLimitBreached",
    summary: null,
    severity: "low",
    status: "RESOLVED",
    alert_count: 14,
    first_alert_at: minutesAgo(95),
    last_alert_at: minutesAgo(80),
    ewma_rate: 0,
    route_decision: "suppressed",
    quiet_at_ms: now + 14 * 60_000,
    root_cause_hint: null,
    created_at: minutesAgo(95),
    updated_at: minutesAgo(80),
  },
  {
    incident_id: "demo-9",
    title: "cdn-edge · OriginTimeout",
    summary: null,
    severity: "low",
    status: "QUIESCENT",
    alert_count: 9,
    first_alert_at: minutesAgo(66),
    last_alert_at: minutesAgo(35),
    ewma_rate: 0.1,
    route_decision: "suppressed",
    quiet_at_ms: now + 14 * 60_000,
    root_cause_hint: null,
    created_at: minutesAgo(66),
    updated_at: minutesAgo(35),
  },
];

export const DEMO_EDGES: IncidentEdge[] = [
  { src_incident_id: "demo-1", dst_incident_id: "demo-2", weight: 3.2, last_seen_at: minutesAgo(1) },
  { src_incident_id: "demo-2", dst_incident_id: "demo-3", weight: 2.1, last_seen_at: minutesAgo(2) },
  { src_incident_id: "demo-1", dst_incident_id: "demo-8", weight: 0.6, last_seen_at: minutesAgo(80) },
  { src_incident_id: "demo-4", dst_incident_id: "demo-5", weight: 0.9, last_seen_at: minutesAgo(9) },
  { src_incident_id: "demo-1", dst_incident_id: "demo-4", weight: 1.4, last_seen_at: minutesAgo(9) },
];
