import type { Incident, IncidentEdge } from "./types";

// Sample data shown only when the backend is unreachable, so the console
// never presents as a dead page · always paired with a visible "demo data"
// label (see ConnectionStatus / the banner in page.tsx). Never shown while
// the API is actually reachable, even if it legitimately has zero incidents.
const now = Date.now();
const minutesAgo = (m: number) => new Date(now - m * 60_000).toISOString();

export const DEMO_INCIDENTS: Incident[] = [
  {
    incident_id: "demo-1",
    title: "payment-api · ServiceDown",
    summary: "Health check failing on 2 of 3 instances.",
    severity: "critical",
    status: "active",
    alert_count: 47,
    first_alert_at: minutesAgo(18),
    last_alert_at: minutesAgo(1),
    ewma_rate: 3.8,
    route_decision: "pagerduty",
    root_cause_hint: "payment-api deploy at 10:02 correlates with onset",
    created_at: minutesAgo(18),
    updated_at: minutesAgo(1),
  },
  {
    incident_id: "demo-2",
    title: "payment-api · HighCPUUsage",
    summary: "CPU above 90% on payment-api-1, payment-api-2.",
    severity: "high",
    status: "active",
    alert_count: 112,
    first_alert_at: minutesAgo(22),
    last_alert_at: minutesAgo(2),
    ewma_rate: 5.1,
    route_decision: "slack",
    root_cause_hint: null,
    created_at: minutesAgo(22),
    updated_at: minutesAgo(2),
  },
  {
    incident_id: "demo-3",
    title: "checkout-db · ReplicationLagHigh",
    summary: "Replica lag exceeded 30s threshold.",
    severity: "high",
    status: "new",
    alert_count: 9,
    first_alert_at: minutesAgo(4),
    last_alert_at: minutesAgo(1),
    ewma_rate: 1.2,
    route_decision: "slack",
    root_cause_hint: null,
    created_at: minutesAgo(4),
    updated_at: minutesAgo(1),
  },
  {
    incident_id: "demo-4",
    title: "auth-service · ElevatedLatencyP99",
    summary: null,
    severity: "medium",
    status: "quiet",
    alert_count: 26,
    first_alert_at: minutesAgo(41),
    last_alert_at: minutesAgo(15),
    ewma_rate: 0.4,
    route_decision: "slack",
    root_cause_hint: null,
    created_at: minutesAgo(41),
    updated_at: minutesAgo(15),
  },
  {
    incident_id: "demo-5",
    title: "search-index · QueueDepthGrowing",
    summary: null,
    severity: "medium",
    status: "new",
    alert_count: 3,
    first_alert_at: minutesAgo(2),
    last_alert_at: minutesAgo(2),
    ewma_rate: 0.1,
    route_decision: "email",
    root_cause_hint: null,
    created_at: minutesAgo(2),
    updated_at: minutesAgo(2),
  },
  {
    incident_id: "demo-6",
    title: "image-resizer · DiskUsageWarning",
    summary: null,
    severity: "low",
    status: "quiet",
    alert_count: 6,
    first_alert_at: minutesAgo(58),
    last_alert_at: minutesAgo(30),
    ewma_rate: 0.05,
    route_decision: "email",
    root_cause_hint: null,
    created_at: minutesAgo(58),
    updated_at: minutesAgo(30),
  },
  {
    incident_id: "demo-7",
    title: "notifications-worker · PodCrashLoop",
    summary: "Resolved after rollback to previous image.",
    severity: "high",
    status: "resolved",
    alert_count: 84,
    first_alert_at: minutesAgo(120),
    last_alert_at: minutesAgo(75),
    ewma_rate: 0.0,
    route_decision: "pagerduty",
    root_cause_hint: "notifications-worker image rollback resolved this",
    created_at: minutesAgo(120),
    updated_at: minutesAgo(75),
  },
  {
    incident_id: "demo-8",
    title: "payment-api · RateLimitBreached",
    summary: null,
    severity: "low",
    status: "resolved",
    alert_count: 14,
    first_alert_at: minutesAgo(95),
    last_alert_at: minutesAgo(80),
    ewma_rate: 0.0,
    route_decision: "suppressed",
    root_cause_hint: null,
    created_at: minutesAgo(95),
    updated_at: minutesAgo(80),
  },
];

export const DEMO_EDGES: IncidentEdge[] = [
  { src_incident_id: "demo-1", dst_incident_id: "demo-2", weight: 3.2, last_seen_at: minutesAgo(1) },
  { src_incident_id: "demo-2", dst_incident_id: "demo-3", weight: 1.4, last_seen_at: minutesAgo(2) },
  { src_incident_id: "demo-1", dst_incident_id: "demo-8", weight: 0.6, last_seen_at: minutesAgo(80) },
  { src_incident_id: "demo-4", dst_incident_id: "demo-5", weight: 0.5, last_seen_at: minutesAgo(2) },
];
